function N5_Group = average_group_n5( ...
    N5_Subj,...
    cfgN5)

subs = fieldnames(N5_Subj);

metrics = { ...
    'MeanAmplitude',...
    'PeakAmplitude',...
    'PeakLatency',...
    'PeakToPeak',...
    'AUC',...
    'NegativeArea'};

conds = { ...
    'Consonant',...
    'Dissonant',...
    'Difference'};

N5_Group = struct();

for r = 1:numel(cfgN5.analysis_rois)

    roiName = cfgN5.analysis_rois{r};

    for iw = 1:numel(cfgN5.window_names)

        winName = ...
            cfgN5.window_names{iw};

        for ic = 1:numel(conds)

            condName = conds{ic};

            for im = 1:numel(metrics)

                metric = metrics{im};

                values = nan(1,numel(subs));

                for is = 1:numel(subs)

                    values(end+1) = ...
                        N5_Subj.(subs{is}) ...
                        .(roiName) ...
                        .(winName) ...
                        .(condName) ...
                        .(metric);

                end

                N5_Group.(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .(metric).mean = ...
                    mean(values);

                N5_Group.(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .(metric).std = ...
                    std(values);

                N5_Group.(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .(metric).sem = ...
                    std(values)/sqrt(numel(values));

            end
        end
    end
end