function SPN_Group = average_group_spn( ...
    SPN_Subj,...
    cfgSPN)

subs = fieldnames(SPN_Subj);

metrics = { ...
    'MeanAmplitude',...
    'AUC',...
    'NegativeArea',...
    'Slope'};

conds = { ...
    'Consonant',...
    'Dissonant',...
    'Difference'};

SPN_Group = struct();

for r = 1:numel(cfgSPN.analysis_rois)

    roiName = cfgSPN.analysis_rois{r};

    for iw = 1:numel(cfgSPN.window_names)

        winName = ...
            cfgSPN.window_names{iw};

        for ic = 1:numel(conds)

            condName = conds{ic};

            for im = 1:numel(metrics)

                metric = metrics{im};

                values = nan(1,numel(subs));

                for is = 1:numel(subs)

                    values(is) = ...
                        SPN_Subj.(subs{is}) ...
                        .(roiName) ...
                        .(winName) ...
                        .(condName) ...
                        .(metric);

                end

                SPN_Group.(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .(metric).mean = ...
                    mean(values,'omitnan');

                SPN_Group.(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .(metric).std = ...
                    std(values,'omitnan');

                SPN_Group.(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .(metric).sem = ...
                    std(values,'omitnan') / ...
                    sqrt(sum(~isnan(values)));

                SPN_Group.(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .(metric).n = ...
                    sum(~isnan(values));

            end

        end

    end

end

end