function MMN_Group = average_group_mmn( ...
    MMN_Subj,...
    cfgMMN)

subs = fieldnames(MMN_Subj);

metrics = { ...
    'MeanAmplitude',...
    'PeakAmplitude',...
    'PeakLatency',...
    'PeakToPeak',...
    'AUC',...
    'NegativeArea'};

conds = { ...
    'Consonant',...
    'Dissonant',...
    'Difference'};

MMN_Group = struct();

for r = 1:numel(cfgMMN.analysis_rois)

    roiName = cfgMMN.analysis_rois{r};

    for iw = 1:numel(cfgMMN.window_names)

        winName = ...
            cfgMMN.window_names{iw};

        for ic = 1:numel(conds)

            condName = conds{ic};

            for im = 1:numel(metrics)

                metric = metrics{im};

                values = nan(1,numel(subs));

                for is = 1:numel(subs)

                    values(end+1) = ...
                        MMN_Subj.(subs{is}) ...
                        .(roiName) ...
                        .(winName) ...
                        .(condName) ...
                        .(metric);

                end

                MMN_Group.(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .(metric).mean = ...
                    mean(values);

                MMN_Group.(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .(metric).std = ...
                    std(values);

                MMN_Group.(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .(metric).sem = ...
                    std(values)/sqrt(numel(values));

            end
        end
    end
end