function ERAN_Group = average_group_eran( ...
    ERAN_Subj,...
    cfgERAN)

subs = fieldnames(ERAN_Subj);

metrics = { ...
    'MeanAmplitude',...
    'PeakAmplitude',...
    'PeakLatency',...
    'PeakToPeak',...
    'AUC',...
    'NegativeArea'};

conds = { ...
    'Consonant',...
    'Dissonant',...
    'Difference'};

ERAN_Group = struct();

for r = 1:numel(cfgERAN.analysis_rois)

    roiName = cfgERAN.analysis_rois{r};

    for iw = 1:numel(cfgERAN.window_names)

        winName = ...
            cfgERAN.window_names{iw};

        for ic = 1:numel(conds)

            condName = conds{ic};

            for im = 1:numel(metrics)

                metric = metrics{im};

                values = nan(1,numel(subs));

                for is = 1:numel(subs)

                    values(end+1) = ...
                        ERAN_Subj.(subs{is}) ...
                        .(roiName) ...
                        .(winName) ...
                        .(condName) ...
                        .(metric);

                end

                ERAN_Group.(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .(metric).mean = ...
                    mean(values);

                ERAN_Group.(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .(metric).std = ...
                    std(values);

                ERAN_Group.(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .(metric).sem = ...
                    std(values)/sqrt(numel(values));

            end
        end
    end
end