function classifier_toolbox_check(classifierName)

classifierName = ...
    upper(char(classifierName));

switch classifierName

    case { ...
            'LDA',...
            'QDA',...
            'LOGREG',...
            'KNN',...
            'NB',...
            'SVC',...
            'TREE',...
            'RF',...
            'BAG',...
            'ADABOOST',...
            'RUSBOOST',...
            'SUBSPACE',...
            'ENSEMBLE',...
            'ECOC'}

        assert( ...
            license('test',...
            'Statistics_Toolbox'),...
            ['Statistics and Machine Learning Toolbox ' ...
            'not available']);

    case { ...
            'ANN',...
            'MLP',...
            'CNN',...
            'LSTM'}

        assert( ...
            license('test',...
            'Neural_Network_Toolbox'),...
            ['Deep Learning Toolbox ' ...
            'not available']);

    otherwise

        warning( ...
            'No toolbox rule defined for %s',...
            classifierName);

end

end