function val = ...
    compute_gamma_mean( ...
    tr,...
    roiLabels,...
    chanLabels,...
    cfg)

roiIdx = ...
    find(ismember( ...
    chanLabels,...
    upper(string(roiLabels))));

if isempty(roiIdx)

    val = NaN;
    return

end

eegROI = ...
    mean( ...
    double(tr.eeg(roiIdx,:)),...
    1);

powerMap = ...
    compute_induced_power( ...
    eegROI,...
    cfg.freqs,...
    tr.srate,...
    cfg.nCycles);

powerMap = ...
    Parker_baseline_correct_tfr( ...
    powerMap,...
    tr.time,...
    cfg.baseline_win);

idxFreq = ...
    cfg.freqs >= cfg.gamma_freq_win(1) & ...
    cfg.freqs <= cfg.gamma_freq_win(2);

idxTime = ...
    tr.time >= cfg.gamma_time_win(1) & ...
    tr.time <= cfg.gamma_time_win(2);

val = ...
    mean( ...
    powerMap(idxFreq,idxTime), ...
    'all',...
    'omitnan');