function [EEGout,FeatureNames] = ...
    compute_tfr_informed_features( ...
    EEGin,...
    cfg,...
    SignalField)

%% ============================================================
% FEATURES
%% ============================================================

FeatureNames = { ...
    'ERAN_CORE_GammaMean'
    'MMN_GammaMean'
    'ERAN_RIGHT_GammaMean'
    'N5_CENTRAL_GammaMean'
    };

nFeatures = ...
    numel(FeatureNames);

EEGout = EEGin;

%% ============================================================
% LOOP
%% ============================================================

for iTr = 1:numel(EEGin)

    tr = EEGin(iTr);

    featureVector = ...
        nan(1,nFeatures);

    chanLabels = ...
        upper(string({tr.chanlocs.labels}));

    featureVector(1) = ...
        compute_gamma_mean( ...
        tr,...
        cfg.rois.ERAN_CORE,...
        chanLabels,...
        cfg);

    featureVector(2) = ...
        compute_gamma_mean( ...
        tr,...
        cfg.rois.MMN,...
        chanLabels,...
        cfg);

    featureVector(3) = ...
        compute_gamma_mean( ...
        tr,...
        cfg.rois.ERAN_RIGHT,...
        chanLabels,...
        cfg);

    featureVector(4) = ...
        compute_gamma_mean( ...
        tr,...
        cfg.rois.N5_CENTRAL,...
        chanLabels,...
        cfg);

    EEGout(iTr).(SignalField) = ...
        featureVector;

    EEGout(iTr).(['time' SignalField]) = ...
        1:nFeatures;

end

end