function [out,FeatureNames] = ...
    compute_tfr_grid_features( ...
    tr,...
    cfg,...
    outField)

Features = [];
FeatureNames = {};

timeVec = tr.time;
Fs = tr.srate;

for iROI = 1:numel(cfg.analysis_rois)

    roiName = cfg.analysis_rois{iROI};

    roiLabels = ...
        cfg.rois.(roiName);

    chanLabels = ...
        {tr.chanlocs.labels};

    roiIdx = ...
        ismember( ...
        chanLabels,...
        roiLabels);

    if ~any(roiIdx)
        continue
    end

    roiSignal = ...
        mean( ...
        tr.eeg(roiIdx,:),...
        1);

    %% --------------------------------------------------------
    % TFR
    %% --------------------------------------------------------

    powerTF = ...
        compute_induced_power( ...
        roiSignal,...
        cfg.freqs,...
        Fs,...
        cfg.nCycles);

    %% --------------------------------------------------------
    % Baseline
    %% --------------------------------------------------------

    idxBase = ...
        timeVec >= cfg.baseline_win(1) & ...
        timeVec <= cfg.baseline_win(2);

    baseMean = ...
        mean(powerTF(:,idxBase),2);

    powerTF = ...
        10 .* log10( ...
        powerTF ./ baseMean);

    %% --------------------------------------------------------
    % GRID
    %% --------------------------------------------------------

    freqEdges = ...
        cfg.freq_bin_edges;

    timeEdges = ...
        cfg.time_bin_edges;

    for iF = 1:(numel(freqEdges)-1)

        f1 = freqEdges(iF);
        f2 = freqEdges(iF+1);

        freqIdx = ...
            cfg.freqs >= f1 & ...
            cfg.freqs < f2;

        for iT = 1:(numel(timeEdges)-1)

            t1 = timeEdges(iT);
            t2 = timeEdges(iT+1);

            timeIdx = ...
                timeVec >= t1 & ...
                timeVec < t2;

            value = ...
                mean( ...
                powerTF(freqIdx,timeIdx), ...
                'all');

            Features(end+1) = value;

            FeatureNames{end+1,1} = ...
                sprintf( ...
                '%s_F%02d_T%02d',...
                roiName,...
                iF,...
                iT);

        end
    end
end

out = struct();

out.(outField) = Features;

out.(['time' outField]) = ...
    1:numel(Features);