function [EEGout,FeatureNames] = ...
    compute_erp_informed_features( ...
    EEGin,...
    cfgINF,...
    SignalField)

%% ============================================================
% FEATURE DEFINITIONS
%% ============================================================

nFeatures = 16;

FeatureNames = { ...
    'ERAN_CORE_ERPIndex'
    'MMN_ERPIndex'
    'ERAN_RIGHT_ERPIndex'
    'N5_CENTRAL_ERPIndex'

    'ERAN_CORE_ERAN_B_Mean'
    'ERAN_CORE_ERAN_B_AUC'

    'MMN_ERAN_B_Mean'
    'MMN_ERAN_B_AUC'

    'ERAN_CORE_ERAN_B_MinPeak'
    'MMN_ERAN_B_MinPeak'

    'N5_CENTRAL_BetaLow_REB_A'
    'N5_CENTRAL_BetaLow_REB_B'

    'MMN_BetaLow_REB_A'
    'MMN_BetaLow_REB_B'

    'N5_CENTRAL_BetaLow_ERAN_A'
    'N5_CENTRAL_BetaLow_ERAN_B'
    };

EEGout = EEGin;

%% ============================================================
% WINDOWS
%% ============================================================

ERAN_A = [0.170 0.195];
ERAN_B = [0.195 0.220];

REB_A  = [0.220 0.270];
REB_B  = [0.270 0.320];

%% ============================================================
% BAND
%% ============================================================

BetaLow = [13 20];

%% ============================================================
% TRIAL LOOP
%% ============================================================

for iTr = 1:numel(EEGin)

    tr = EEGin(iTr);

    featureVector = ...
        nan(1,nFeatures);

    chanLabels = ...
        upper(string({tr.chanlocs.labels}));

    %% ========================================================
    % ERPINDEX FEATURES
    %% ========================================================

    featureVector(1) = ...
        computeERPIndex( ...
        tr,...
        cfgINF.rois.ERAN_CORE,...
        chanLabels,...
        ERAN_A,...
        ERAN_B,...
        REB_A,...
        REB_B);

    featureVector(2) = ...
        computeERPIndex( ...
        tr,...
        cfgINF.rois.MMN,...
        chanLabels,...
        ERAN_A,...
        ERAN_B,...
        REB_A,...
        REB_B);

    featureVector(3) = ...
        computeERPIndex( ...
        tr,...
        cfgINF.rois.ERAN_RIGHT,...
        chanLabels,...
        ERAN_A,...
        ERAN_B,...
        REB_A,...
        REB_B);

    featureVector(4) = ...
        computeERPIndex( ...
        tr,...
        cfgINF.rois.N5_CENTRAL,...
        chanLabels,...
        ERAN_A,...
        ERAN_B,...
        REB_A,...
        REB_B);

    %% ========================================================
    % ERAN_B FEATURES
    %% ========================================================

    [featureVector(5),...
     featureVector(6),...
     featureVector(9)] = ...
        computeERANBFeatures( ...
        tr,...
        cfgINF.rois.ERAN_CORE,...
        chanLabels,...
        ERAN_B);

    [featureVector(7),...
     featureVector(8),...
     featureVector(10)] = ...
        computeERANBFeatures( ...
        tr,...
        cfgINF.rois.MMN,...
        chanLabels,...
        ERAN_B);

    %% ========================================================
    % BETALOW FEATURES
    %% ========================================================

    featureVector(11) = ...
        computeBandWindow( ...
        tr,...
        cfgINF.rois.N5_CENTRAL,...
        chanLabels,...
        BetaLow,...
        REB_A,...
        cfgINF);

    featureVector(12) = ...
        computeBandWindow( ...
        tr,...
        cfgINF.rois.N5_CENTRAL,...
        chanLabels,...
        BetaLow,...
        REB_B,...
        cfgINF);

    featureVector(13) = ...
        computeBandWindow( ...
        tr,...
        cfgINF.rois.MMN,...
        chanLabels,...
        BetaLow,...
        REB_A,...
        cfgINF);

    featureVector(14) = ...
        computeBandWindow( ...
        tr,...
        cfgINF.rois.MMN,...
        chanLabels,...
        BetaLow,...
        REB_B,...
        cfgINF);

    featureVector(15) = ...
        computeBandWindow( ...
        tr,...
        cfgINF.rois.N5_CENTRAL,...
        chanLabels,...
        BetaLow,...
        ERAN_A,...
        cfgINF);

    featureVector(16) = ...
        computeBandWindow( ...
        tr,...
        cfgINF.rois.N5_CENTRAL,...
        chanLabels,...
        BetaLow,...
        ERAN_B,...
        cfgINF);

    %% ========================================================
    % STORE
    %% ========================================================

    EEGout(iTr).(SignalField) = ...
        featureVector;

    %% campo temporale richiesto da mdlPredict

    EEGout(iTr).(['time' SignalField]) = ...
        1:nFeatures;

    EEGout(iTr).trialType = ...
        tr.trialType;

end

end
function val = ...
    computeERPIndex( ...
    tr,...
    roiLabels,...
    chanLabels,...
    ERAN_A,...
    ERAN_B,...
    REB_A,...
    REB_B)

roiIdx = ...
    find(ismember( ...
    chanLabels,...
    upper(string(roiLabels))));

if isempty(roiIdx)
    val = NaN;
    return
end

sig = ...
    mean( ...
    double(tr.eeg(roiIdx,:)),...
    1);

idxERAN = ...
    tr.time >= ERAN_A(1) & ...
    tr.time <= ERAN_B(2);

idxREB = ...
    tr.time >= REB_A(1) & ...
    tr.time <= REB_B(2);

val = ...
    mean(sig(idxREB)) - ...
    mean(sig(idxERAN));

end
function [m,a,p] = ...
    computeERANBFeatures( ...
    tr,...
    roiLabels,...
    chanLabels,...
    ERAN_B)

roiIdx = ...
    find(ismember( ...
    chanLabels,...
    upper(string(roiLabels))));

if isempty(roiIdx)
    m = NaN;
    a = NaN;
    p = NaN;
    return
end

sig = ...
    mean( ...
    double(tr.eeg(roiIdx,:)),...
    1);

idx = ...
    tr.time >= ERAN_B(1) & ...
    tr.time <= ERAN_B(2);

seg = sig(idx);

m = mean(seg);

a = trapz( ...
    tr.time(idx),...
    seg);

p = min(seg);

end
function val = ...
    computeBandWindow( ...
    tr,...
    roiLabels,...
    chanLabels,...
    bandRange,...
    window,...
    cfgINF)

roiIdx = ...
    find(ismember( ...
    chanLabels,...
    upper(string(roiLabels))));

if isempty(roiIdx)
    val = NaN;
    return
end

eegROI = ...
    double( ...
    tr.eeg(roiIdx,:));

roiPower = ...
    nan(size(eegROI));
cgfINF = cfgINF;
for ch = 1:size(eegROI,1)

    sig = eegROI(ch,:);

    sigF = ...
        bandpass( ...
        sig,...
        bandRange,...
        tr.srate);

    H = hilbert(sigF);

    P = abs(H).^2;

    idxBase = ...
        tr.time >= -0.2 & ...
        tr.time <= 0;

    base = ...
        mean(P(idxBase));

    if base <= 0 || isnan(base)
        base = eps;
    end
    
    roiPower(ch,:) = ...
        10*log10(P/base);

end

roiWave = ...
    mean(roiPower,1);

idx = ...
    tr.time >= window(1) & ...
    tr.time <= window(2);

val = ...
    mean(roiWave(idx));

end