function wavelet = create_morlet_wavelet( ...
    freq,...
    nCycles,...
    Fs)

% ============================================================
% CREATE_MORLET_WAVELET
%
% Complex Morlet wavelet
%
% ============================================================

sigma_t = ...
    nCycles/(2*pi*freq);

t = -3.5*sigma_t : ...
    1/Fs : ...
    3.5*sigma_t;

wavelet = ...
    exp(2*1i*pi*freq.*t) ...
    .* exp(-(t.^2) ./ (2*sigma_t^2));

% energy normalization

wavelet = ...
    wavelet ./ sqrt(sum(abs(wavelet).^2));