function MMN_Subj = extract_mmn_metrics( ...
    subj_list,...
    cfgMMN)

MMN_Subj = struct();

for iSub = 1:numel(subj_list)

    subj_curr = subj_list(iSub);

    subjID = matlab.lang.makeValidName( ...
        char(subj_curr.subj_id));

    fprintf('[%02d/%02d] %s\n', ...
        iSub,...
        numel(subj_list),...
        subjID);

    data_trials = subj_curr.data_trials;

    timeVec = data_trials(1).time;

    for r = 1:numel(cfgMMN.analysis_rois)

        roiName = cfgMMN.analysis_rois{r};

        roi_labels = ...
            cfgMMN.rois.(roiName);

        ERP = struct();

        for ic = 1:numel(cfgMMN.conditions)

            condName = cfgMMN.conditions{ic};

            idxCond = strcmp( ...
                {data_trials.(cfgMMN.cond_field)}, ...
                condName);

            trials_cond = data_trials(idxCond);
            if isempty(trials_cond)

                warning('%s | %s has no trials', ...
                    subjID,...
                    condName);

                continue

            end
            ERP_trials = nan( ...
                numel(trials_cond), ...
                size(trials_cond(1).eeg,2));

            for iTr = 1:numel(trials_cond)

                eeg = trials_cond(iTr).eeg;

                labels = ...
                    {trials_cond(iTr).chanlocs.labels};

                roi_idx = ...
                    ismember(labels,roi_labels);

                roi_signal = ...
                    mean(eeg(roi_idx,:),1);

                ERP_trials(iTr,:) = roi_signal;

            end

            ERP.(condName) = ...
                mean(ERP_trials,1);

        end

        ERP.Difference = ...
            ERP.Dissonant - ...
            ERP.Consonant;

        for iw = 1:numel(cfgMMN.windows)

            win = cfgMMN.windows{iw};

            winName = ...
                cfgMMN.window_names{iw};

            idxWin = ...
                timeVec >= win(1) & ...
                timeVec <= win(2);

            timeWin = ...
                timeVec(idxWin);

            conds = { ...
                'Consonant',...
                'Dissonant',...
                'Difference'};

            for ic = 1:numel(conds)

                condName = conds{ic};

                signalWin = ...
                    ERP.(condName)(idxWin);

                MeanAmplitude = ...
                    mean(signalWin);

                [PeakAmplitude,idxPeak] = ...
                    min(signalWin);

                PeakLatency = ...
                    timeWin(idxPeak);

                PeakToPeak = ...
                    max(signalWin) - ...
                    min(signalWin);

                AUC = ...
                    trapz(timeWin,signalWin);

                signalNeg = signalWin;

                signalNeg(signalNeg > 0) = 0;

                NegativeArea = ...
                    trapz(timeWin,signalNeg);

                MMN_Subj.(subjID) ...
                    .(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .MeanAmplitude = MeanAmplitude;

                MMN_Subj.(subjID) ...
                    .(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .PeakAmplitude = PeakAmplitude;

                MMN_Subj.(subjID) ...
                    .(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .PeakLatency = PeakLatency;

                MMN_Subj.(subjID) ...
                    .(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .PeakToPeak = PeakToPeak;

                MMN_Subj.(subjID) ...
                    .(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .AUC = AUC;

                MMN_Subj.(subjID) ...
                    .(roiName) ...
                    .(winName) ...
                    .(condName) ...
                    .NegativeArea = NegativeArea;

            end
        end
    end
end