function stats = extract_tfr_window( ...
    dataStruct,...
    freqRange,...
    timeRange)

% ============================================================
% EXTRACT_TFR_WINDOW
%
% Extract average power within a predefined
% frequency-time window.
%
% ============================================================

freqIdx = ...
    dataStruct.freq >= freqRange(1) & ...
    dataStruct.freq <= freqRange(2);

timeIdx = ...
    dataStruct.time >= timeRange(1) & ...
    dataStruct.time <= timeRange(2);

assert(any(freqIdx), ...
    'No frequencies selected');

assert(any(timeIdx), ...
    'No time points selected');

stats.freqRange = freqRange;
stats.timeRange = timeRange;

stats.Consonant = mean( ...
    dataStruct.Consonant.power( ...
    freqIdx,timeIdx), ...
    'all');

stats.Dissonant = mean( ...
    dataStruct.Dissonant.power( ...
    freqIdx,timeIdx), ...
    'all');

stats.Difference = ...
    stats.Consonant - ...
    stats.Dissonant;