function filtered_data = ...
    FiltBankERPGuided( ...
    data_eeg,...
    par)

% =============================================================
% FiltBankERPGuided
%
% ERP-guided filterbank derived from ERP-informed analyses.
%
% Bands:
%
%   1) Theta    4-7 Hz
%   2) Alpha    8-12 Hz
%   3) BetaLow 13-20 Hz
%   4) BetaMid 20-30 Hz
%
% Output:
%
%   [Channels x Samples x 4]
%
% =============================================================

%% ============================================================
% PARAMETERS
%% ============================================================

order = ...
    par.order;

attenuation = ...
    par.attenuation;

fsamp = ...
    par.fsample;

%% ============================================================
% OUTPUT INIT
%% ============================================================

nCh = ...
    size(data_eeg,1);

nTime = ...
    size(data_eeg,2);

filtered_data = ...
    zeros( ...
    nCh,...
    nTime,...
    4);

%% ============================================================
% THETA
% 4-7 Hz
%% ============================================================

filtered_data(:,:,1) = ...
    localBandpass( ...
    data_eeg,...
    [4 7],...
    order,...
    attenuation,...
    fsamp,...
    par.TypeFilter);

%% ============================================================
% ALPHA
% 8-12 Hz
%% ============================================================

filtered_data(:,:,2) = ...
    localBandpass( ...
    data_eeg,...
    [8 12],...
    order,...
    attenuation,...
    fsamp,...
    par.TypeFilter);

%% ============================================================
% BETALOW
% 13-20 Hz
%% ============================================================

filtered_data(:,:,3) = ...
    localBandpass( ...
    data_eeg,...
    [13 20],...
    order,...
    attenuation,...
    fsamp,...
    par.TypeFilter);

%% ============================================================
% BETAMID
% 20-30 Hz
%% ============================================================

filtered_data(:,:,4) = ...
    localBandpass( ...
    data_eeg,...
    [20 30],...
    order,...
    attenuation,...
    fsamp,...
    par.TypeFilter);

end

%% ========================================================================
% LOCAL FUNCTION
%% ========================================================================

function Y = ...
    localBandpass( ...
    X,...
    bandRange,...
    order,...
    attenuation,...
    fsamp,...
    filterType)

lowCut = bandRange(1);

highCut = bandRange(2);

if strcmp(filterType,'Chebyshev')

    [z,p,k] = ...
        cheby2( ...
        order,...
        attenuation,...
        2*[lowCut highCut]/fsamp);

elseif strcmp(filterType,'Butterworth')

    [z,p,k] = ...
        butter( ...
        order,...
        2*[lowCut highCut]/fsamp,...
        'bandpass');

else

    error( ...
        'Unknown filter type: %s',...
        filterType);

end

[sos,g] = ...
    zp2sos(z,p,k);

Y = ...
    zeros(size(X));

for iCh = 1:size(X,1)

    Y(iCh,:) = ...
        filtfilt( ...
        sos,...
        g,...
        X(iCh,:));

end

end