function old_plot_spn_zoom( ...
    subj_list_spn,...
    cfgSPN,...
    outdir)

%% ============================================================
% DEFAULTS
%% ============================================================
if ~isfield(cfgSPN,'smooth_plot')
    cfgSPN.smooth_plot = false;
end

if ~isfield(cfgSPN,'smooth_window')
    cfgSPN.smooth_window = 5;
end

if ~isfield(cfgSPN,'smooth_slope')
    cfgSPN.smooth_slope = false;
end

assert( ...
    isnumeric(cfgSPN.smooth_window) && ...
    isscalar(cfgSPN.smooth_window) && ...
    cfgSPN.smooth_window >= 1 && ...
    mod(cfgSPN.smooth_window,1) == 0,...
    'cfgSPN.smooth_window must be a positive integer');

%% ============================================================
% OUTPUT DIRECTORY
%% ============================================================
zoomDir = fullfile(outdir,'Zoom');

if ~exist(zoomDir,'dir')
    mkdir(zoomDir);
end

%% ============================================================
% LOOP ROIs
%% ============================================================
for r = 1:numel(cfgSPN.analysis_rois)

    roiName = cfgSPN.analysis_rois{r};

    roi_labels = ...
        cfgSPN.rois.(roiName);

    %% ========================================================
    % PREALLOCATE SUBJECT MATRICES
    %% ========================================================
    nSub = numel(subj_list_spn);

    timeVec = ...
        subj_list_spn(1).data_trials(1).time;

    nTime = numel(timeVec);

    ERP_CON = nan(nSub,nTime);
    ERP_DIS = nan(nSub,nTime);

    %% ========================================================
    % SUBJECT LOOP
    %% ========================================================
    for iSub = 1:nSub

        data_trials = ...
            subj_list_spn(iSub).data_trials;

        labels = ...
            {data_trials(1).chanlocs.labels};

        roi_idx = ...
            ismember(labels,roi_labels);

        idxCon = strcmp( ...
            {data_trials.eventLabel},...
            'Consonant');

        idxDis = strcmp( ...
            {data_trials.eventLabel},...
            'Dissonant');

        conTrials = find(idxCon);
        disTrials = find(idxDis);

        nCon = numel(conTrials);
        nDis = numel(disTrials);

        ERPcon_trials = ...
            nan(nCon,nTime);

        ERPdis_trials = ...
            nan(nDis,nTime);

        %% ----------------------------------------------------
        % CONSONANT
        %% ----------------------------------------------------
        for k = 1:nCon

            it = conTrials(k);

            ERPcon_trials(k,:) = ...
                mean( ...
                data_trials(it).eeg(roi_idx,:),...
                1,...
                'omitnan');

        end

        %% ----------------------------------------------------
        % DISSONANT
        %% ----------------------------------------------------
        for k = 1:nDis

            it = disTrials(k);

            ERPdis_trials(k,:) = ...
                mean( ...
                data_trials(it).eeg(roi_idx,:),...
                1,...
                'omitnan');

        end

        ERP_CON(iSub,:) = ...
            mean(ERPcon_trials,1,'omitnan');

        ERP_DIS(iSub,:) = ...
            mean(ERPdis_trials,1,'omitnan');

    end

    %% ========================================================
    % GROUP ERP
    %% ========================================================
    ERPcon_raw = ...
        mean(ERP_CON,1,'omitnan');

    ERPdis_raw = ...
        mean(ERP_DIS,1,'omitnan');

    ERPdiff_raw = ...
        ERPdis_raw - ERPcon_raw;

    %% ========================================================
    % OPTIONAL SMOOTHING FOR DISPLAY
    %% ========================================================
    ERPcon_plot = ERPcon_raw;
    ERPdis_plot = ERPdis_raw;
    ERPdiff_plot = ERPdiff_raw;

    if cfgSPN.smooth_plot

        ERPcon_plot = movmean( ...
            ERPcon_raw,...
            cfgSPN.smooth_window,...
            'omitnan');

        ERPdis_plot = movmean( ...
            ERPdis_raw,...
            cfgSPN.smooth_window,...
            'omitnan');

        ERPdiff_plot = movmean( ...
            ERPdiff_raw,...
            cfgSPN.smooth_window,...
            'omitnan');

    end

    %% ========================================================
    % LATE SPN SLOPE
    %% ========================================================
    slopeWindow = ...
        cfgSPN.windows{end};

    idxLate = ...
        timeVec >= slopeWindow(1) & ...
        timeVec <= slopeWindow(2);

    timeLate = ...
        timeVec(idxLate);

    if cfgSPN.smooth_slope

        diffLate = ...
            ERPdiff_plot(idxLate);

    else

        diffLate = ...
            ERPdiff_raw(idxLate);

    end

    validSlope = ...
        isfinite(timeLate) & ...
        isfinite(diffLate);

    timeLate = ...
        timeLate(validSlope);

    diffLate = ...
        diffLate(validSlope);

    if numel(timeLate) >= 2

        p = polyfit( ...
            timeLate,...
            diffLate,...
            1);

        slopeVal = p(1);

        fitLine = polyval( ...
            p,...
            timeLate);

    else

        slopeVal = NaN;
        fitLine = nan(size(timeLate));

    end

    %% ========================================================
    % WINDOW LABELS
    %% ========================================================
    nWindows = ...
        numel(cfgSPN.windows);

    winLabels = ...
        cell(1,nWindows);

    for iw = 1:nWindows

        win = ...
            cfgSPN.windows{iw};

        winLabels{iw} = ...
            sprintf( ...
            '%s (%d-%d ms)',...
            format_tex_name(cfgSPN.window_names{iw}),...
            round(win(1)*1000),...
            round(win(2)*1000));

    end

    %% ========================================================
    % FIGURE
    %% ========================================================
    figure( ...
        'Color','w',...
        'Position',[100 100 1200 600]);

    hold on

    allY = [ ...
        ERPcon_plot ...
        ERPdis_plot ...
        ERPdiff_plot];

    yL = [ ...
        min(allY,[],'omitnan') ...
        max(allY,[],'omitnan')];

    if any(~isfinite(yL)) || yL(1) == yL(2)

        yL = [-1 1];

    end

    %% ========================================================
    % WINDOWS
    %% ========================================================
    colors = ...
        lines(nWindows);

    patchHandles = ...
        gobjects(nWindows,1);

    for iw = 1:nWindows

        win = ...
            cfgSPN.windows{iw};

        patchHandles(iw) = ...
            patch( ...
            [win(1) win(2) win(2) win(1)],...
            [yL(1) yL(1) yL(2) yL(2)],...
            colors(iw,:),...
            'FaceAlpha',0.08,...
            'EdgeColor','none');

    end

    %% ========================================================
    % ERP CURVES
    %% ========================================================
    hCon = plot( ...
        timeVec,...
        ERPcon_plot,...
        'LineWidth',2);

    hDis = plot( ...
        timeVec,...
        ERPdis_plot,...
        'LineWidth',2);

    hDiff = plot( ...
        timeVec,...
        ERPdiff_plot,...
        'k',...
        'LineWidth',2);

    %% ========================================================
    % SPN SLOPE FIT
    %% ========================================================
    hSlope = plot( ...
        timeLate,...
        fitLine,...
        'r--',...
        'LineWidth',2.5);

    %% ========================================================
    % REFERENCES
    %% ========================================================
    yline( ...
        0,...
        'k:');

    xline( ...
        0,...
        'r:',...
        'LineWidth',1.5);

    %% ========================================================
    % AXES
    %% ========================================================
    xlim(cfgSPN.zoom_window)

    xlabel('Time (s)')
    ylabel('\muV')

    if cfgSPN.smooth_plot

        smoothText = sprintf( ...
            ', smoothed: %d samples',...
            cfgSPN.smooth_window);

    else

        smoothText = ', raw';

    end

    title(sprintf( ...
        '%s SPN Zoom%s\nLate Slope = %.5f',...
        format_tex_name(roiName),...
        smoothText,...
        slopeVal));

    %% ========================================================
    % LEGEND
    %% ========================================================
    legendHandles = [ ...
        patchHandles(:)' ...
        hCon ...
        hDis ...
        hDiff ...
        hSlope];

    legendLabels = [ ...
        winLabels,...
        {'Consonant',...
        'Dissonant',...
        'Difference',...
        'SPN Slope'}];

    legend( ...
        legendHandles,...
        legendLabels,...
        'Location','best');

    set(gca,...
        'FontSize',11,...
        'Box','off',...
        'Layer','top');

    %% ========================================================
    % SAVE
    %% ========================================================
    exportgraphics( ...
        gcf,...
        fullfile( ...
        zoomDir,...
        sprintf('%s_SPN_Zoom.png',...
        roiName)),...
        'Resolution',300);

    close

end

end