function OUT = plot_limo_erp_comparison(ERP,cfg)

% PLOT_LIMO_ERP_COMPARISON
%
% Visualizes ROI-based ERP differences between two conditions
% using LIMO robust statistics.
%
% Features:
%   - mean ERP waveforms
%   - trimmed-mean confidence intervals
%   - significant time-point markers
%   - customizable colors and labels
%
% INPUT
%
%   ERP :
%       ROI structure generated by
%       create_group_erp_by_roi
%
%   cfg :
%       conditions
%       alpha
%       trim_percent
%       line_colors
%       title_str
%       save_path
%
% OUTPUT
%
%   OUT.figure
%   OUT.wave1
%   OUT.wave2
%   OUT.ci1
%   OUT.ci2
%   OUT.p_values
%   OUT.sig_mask

if nargin < 2
    cfg = struct();
end

assert(isfield(cfg,'conditions'), ...
    'cfg.conditions is required');

assert(numel(cfg.conditions)==2,...
    'plot_limo_erp_comparison requires exactly 2 conditions');

if ~isfield(cfg,'alpha')
    cfg.alpha = 0.05;
end
if ~isfield(cfg,'ci_alpha')
    cfg.ci_alpha = 0.15;
end
tc = cfg.ci_alpha;
if ~isfield(cfg,'trim_percent')
    cfg.trim_percent = 20;
end
perCnt = cfg.trim_percent;
alpha  = cfg.alpha;
if ~isfield(cfg,'line_colors')
    cfg.line_colors = [
        0 0.4470 0.7410
        0.8500 0.3250 0.0980
        ];
end
lineColor1 = cfg.line_colors(1,:);
lineColor2 = cfg.line_colors(2,:);

patchColor1 = min(lineColor1 + 0.3,1);
patchColor2 = min(lineColor2 + 0.3,1);

legendLab = cfg.conditions;
if isfield(cfg,'start_plot') && isfield(cfg,'end_plot')
    start_plot = cfg.start_plot;
    end_plot = cfg.end_plot;
else
    start_plot = ERP.time(1);
    end_plot = ERP.time(end);
end

cond1 = cfg.conditions{1};
cond2 = cfg.conditions{2};
assert(isfield(ERP,'time'), ...
    'ERP.time missing');

assert(isfield(ERP,cond1), ...
    'First condition not found');

assert(isfield(ERP,cond2), ...
    'Second condition not found');

data1 = ERP.(cond1);
data2 = ERP.(cond2);

assert(ndims(data1)==3, ...
    'Condition 1 must be ROIchannels x Time x Subjects');

assert(ndims(data2)==3, ...
    'Condition 2 must be ROIchannels x Time x Subjects');

erp1 = mean(data1,3,'omitnan');
erp2 = mean(data2,3,'omitnan');

wave1 = mean(erp1,1,'omitnan');
wave2 = mean(erp2,1,'omitnan');


tt = ERP.time(:).';

c1_roi = mean(data1,'omitnan');
c2_roi = mean(data2,'omitnan');

[~,~,~,~,p12,~,~] = limo_yuend_ttest(data1,data2,perCnt,alpha);

figure('Color','w','NumberTitle','off')
hold on
grid on
box off
set(gca,...
    'FontSize',12,...
    'LineWidth',1);
if isfield(cfg,'title_str') && ~isempty(cfg.title_str)
    title(cfg.title_str,'Interpreter','none');
end
nullvalue=0;
[~,~,trimci_c1,~,~,~] = limo_trimci(c1_roi, perCnt, alpha, nullvalue);
[~,~,trimci_c2,~,~,~] = limo_trimci(c2_roi, perCnt, alpha, nullvalue);
% plot confidenC intervals
x = tt; % time vector
yc1 = squeeze(trimci_c1(:,:,1)); % D lower bound
zc1 =squeeze(trimci_c1(:,:,2)); % D upper bound
colorc1 = lineColor1; % set colour

x=x(:)';yc1=yc1(:)';zc1=zc1(:)';
X=[x,fliplr(x)]; % create continuous x value array for plotting
Yc1=[yc1,fliplr(zc1)]; % create y values for out and then back
hfc1=fill(X,Yc1,colorc1); % plot filled area
set(hfc1,'FaceAlpha',tc,'EdgeColor',patchColor1,'LineWidth', 0.1);

yc2=squeeze(trimci_c2(:,:,1));
zc2=squeeze(trimci_c2(:,:,2));
colorc2=lineColor2;
yc2=yc2(:)';
zc2=zc2(:)';
Yc2=[yc2,fliplr(zc2)];%create y values for out and then back
hfc2=fill(X,Yc2,colorc2);%plot filled area
set(hfc2,'FaceAlpha',tc,'EdgeColor',patchColor2,'LineWidth', 0.1);
xline(0,'k--','LineWidth',1);
yline(0,'k:','LineWidth',1);
plot(tt,wave1,'Color',lineColor1,'LineStyle','-','LineWidth',2)
plot(tt,wave2,'Color',lineColor2,'LineStyle','-','LineWidth',2)
set(gca,'LineWidth',1,'FontSize',14,'XLim',[start_plot end_plot])

if max(abs(tt)) < 10
    xlabel('Time (s)');
else
    xlabel('Time (ms)');
end
ylabel('Amplitude in \muV','FontSize',16)

% p_sum12 = sum(p12<=alpha);
% p_title12 = 100*(sum(p_sum12~=0)/length(tt));

box on
hold on;
% We add a horizontal line showing time points at which a significant mean
% differenC was observed.
v=axis; % get current axis limits

sig_mask = any(p12 <= alpha,1);
% ySig = v(3) + 0.05*(v(4)-v(3));
ySig = v(3) + 0.02*(v(4)-v(3));
scatter( ...
    tt(sig_mask), ...
    repmat(ySig,1,sum(sig_mask)), ...
    15,...
    [0.466 0.674 0.188],...
    'filled');
axis(v) % restore axis limits to hide non-significant points

sig_percent = 100 * mean(sig_mask);
subtitle(sprintf( ...
    'Yuen t-test, significant frames: %.1f%%', ...
    sig_percent));
set(gcf,'PaperPositionMode','auto')
set(gcf, 'WindowState', 'maximized');
legend(legendLab(1:2), ...
    'Location','best');

if ~isempty(cfg.save_path)
    [p,~,~] = fileparts(cfg.save_path);
    if ~isempty(p) && ~exist(p,'dir'), mkdir(p); end
    exportgraphics( ...
    gcf,...
    cfg.save_path,...
    'Resolution',300);
end

OUT = struct();
OUT.figure = gcf;
OUT.axes = gca;
OUT.wave1 = wave1;
OUT.wave2 = wave2;
OUT.ci1 = trimci_c1;
OUT.ci2 = trimci_c2;
OUT.p_values = p12;
OUT.time = tt;
OUT.condition1 = cond1;
OUT.condition2 = cond2;
OUT.alpha = alpha;
OUT.trim_percent = perCnt;
OUT.sig_percent = sig_percent;
OUT.sig_mask = sig_mask;
OUT.condition_labels = legendLab;
end