function plot_eran_metrics( ...
    ERAN_Subj,...
    ERAN_Stats,...
    cfgERAN,...
    outdir)

metricDir = ...
    fullfile(outdir,'Metrics');

if ~exist(metricDir,'dir')
    mkdir(metricDir);
end

subs = fieldnames(ERAN_Subj);

metrics = { ...
    'MeanAmplitude',...
    'PeakAmplitude',...
    'PeakLatency',...
    'PeakToPeak',...
    'AUC',...
    'NegativeArea'};

for r = 1:numel(cfgERAN.analysis_rois)

    roiName = cfgERAN.analysis_rois{r};

    for iw = 1:numel(cfgERAN.window_names)

        winName = ...
            cfgERAN.window_names{iw};

        for im = 1:numel(metrics)

            metric = metrics{im};

            con = [];
            dis = [];

            for is = 1:numel(subs)

                con(end+1) = ...
                    ERAN_Subj.(subs{is}) ...
                    .(roiName) ...
                    .(winName) ...
                    .Consonant ...
                    .(metric);

                dis(end+1) = ...
                    ERAN_Subj.(subs{is}) ...
                    .(roiName) ...
                    .(winName) ...
                    .Dissonant ...
                    .(metric);

            end

            p = ...
                ERAN_Stats.(roiName) ...
                .(winName) ...
                .(metric).p;

            d = ...
                ERAN_Stats.(roiName) ...
                .(winName) ...
                .(metric).cohen_d;

            figure( ...
                'Color','w',...
                'Position',[100 100 700 600]);

            hold on

            for k = 1:numel(con)

                plot( ...
                    [1 2],...
                    [con(k) dis(k)],...
                    '-o',...
                    'Color',...
                    [0.6 0.6 0.6]);

            end

            scatter( ...
                ones(size(con)),...
                con,...
                60,...
                [0 0.4470 0.7410],...
                'filled');
            scatter( ...
                2*ones(size(dis)),...
                dis,...
                60,...
                [0.8500 0.3250 0.0980],...
                'filled');

            errorbar( ...
                1,...
                mean(con),...
                std(con)/sqrt(numel(con)),...
                'k',...
                'LineWidth',2);

            errorbar( ...
                2,...
                mean(dis),...
                std(dis)/sqrt(numel(dis)),...
                'k',...
                'LineWidth',2);

            xlim([0.5 2.5])

            xticks([1 2])

            xticklabels({ ...
                'Consonant',...
                'Dissonant'});

            ylabel(metric)

            title(sprintf( ...
                '%s | %s\np=%.4f  d=%.2f',...
                format_tex_name(roiName),...
                format_tex_name(winName),...
                p,...
                d));

            exportgraphics( ...
                gcf,...
                fullfile( ...
                metricDir,...
                sprintf('%s_%s_%s.png', ...
                roiName,...
                winName,...
                metric)),...
                'Resolution',300);

            close

        end
    end
end