function plot_bandpower_waveforms( ...
    GroupBP,...
    roiName,...
    bandName,...
    outdir,...
    cfgPlot)

% ============================================================
% PLOT_BANDPOWER_WAVEFORMS
%
% Creates:
%
% 1) Consonant vs Dissonant
% 2) Difference waveform
%
% ============================================================
if isfield(cfgPlot,'doLIMO')
    doLIMO = cfgPlot.doLIMO;
else
    doLIMO = false;
end
tt = GroupBP.time;

%% ============================================================
% POWER WAVEFORMS
%% ============================================================

fig1 = figure( ...
    'Color','w',...
    'Position',[100 100 1200 600]);

hold on

% ------------------------------------------------------------
% Consonant
% ------------------------------------------------------------

cMean = GroupBP.Consonant.power;
cSEM  = GroupBP.Consonant.sem;

fill( ...
    [tt fliplr(tt)], ...
    [cMean-cSEM fliplr(cMean+cSEM)], ...
    [0.3 0.5 1], ...
    'FaceAlpha',0.25,...
    'EdgeColor','none');

plot( ...
    tt,...
    cMean,...
    'b',...
    'LineWidth',2);

% ------------------------------------------------------------
% Dissonant
% ------------------------------------------------------------

dMean = GroupBP.Dissonant.power;
dSEM  = GroupBP.Dissonant.sem;

fill( ...
    [tt fliplr(tt)], ...
    [dMean-dSEM fliplr(dMean+dSEM)], ...
    [1 0.3 0.3], ...
    'FaceAlpha',0.25,...
    'EdgeColor','none');

plot( ...
    tt,...
    dMean,...
    'r',...
    'LineWidth',2);

% ------------------------------------------------------------
% Axes
% ------------------------------------------------------------

xline(0,'k--');
if isfield(cfgPlot,'plot_window')

    xlim(cfgPlot.plot_window);

end
xlabel('Time (s)');
ylabel('Band Power');

title(sprintf( ...
    '%s | %s', ...
    roiName,...
    bandName));

legend( ...
    {'Consonant SEM',...
     'Consonant',...
     'Dissonant SEM',...
     'Dissonant'}, ...
     'Location','best');

grid on

% ------------------------------------------------------------
% OPTIONAL LIMO STATISTICS
% ------------------------------------------------------------

if doLIMO
    alpha = cfgPlot.alpha;
    c1 = GroupBP.Consonant.subject_values';
    c2 = GroupBP.Dissonant.subject_values';
    percent = 0;
    [~,~,~,~,p,~,~] = ...
        limo_yuend_ttest( ...
        c1,...
        c2,...
        percent,...
        alpha);
    ylim_curr = ylim;
    ySig = ylim_curr(1) + ...
        0.03 * range(ylim_curr);
    sigMask = p <= alpha;
    if any(sigMask)
        plot( ...
            tt(sigMask), ...
            ySig * ones(1,sum(sigMask)), ...
            'k.', ...
            'MarkerSize',12);
    end
end
saveas( ...
    fig1,...
    fullfile( ...
        outdir,...
        sprintf( ...
        'BandPower_%s_%s.png',...
        roiName,...
        bandName)));

close(fig1)

%% ============================================================
% DIFFERENCE WAVEFORM
%% ============================================================

fig2 = figure( ...
    'Color','w',...
    'Position',[100 100 1200 600]);

hold on

diffMean = ...
    GroupBP.Difference.power;

diffSEM = ...
    GroupBP.Difference.sem;

fill( ...
    [tt fliplr(tt)], ...
    [diffMean-diffSEM ...
     fliplr(diffMean+diffSEM)], ...
    [0.5 0.5 0.5], ...
    'FaceAlpha',0.25,...
    'EdgeColor','none');

plot( ...
    tt,...
    diffMean,...
    'k',...
    'LineWidth',2);

yline(0,'k:');

xline(0,'k--');
if isfield(cfgPlot,'plot_window')

    xlim(cfgPlot.plot_window);

end
xlabel('Time (s)');
ylabel('Difference Power');

title(sprintf( ...
    '%s | %s | Difference', ...
    roiName,...
    bandName));

grid on

saveas( ...
    fig2,...
    fullfile( ...
        outdir,...
        sprintf( ...
        'BandPower_Difference_%s_%s.png',...
        roiName,...
        bandName)));

close(fig2)

end