function plot_spn_metrics( ...
    SPN_Subj,...
    SPN_Stats,...
    cfgSPN,...
    outdir)

metricDir = ...
    fullfile(outdir,'Metrics');

if ~exist(metricDir,'dir')
    mkdir(metricDir);
end

subs = fieldnames(SPN_Subj);

metrics = { ...
    'MeanAmplitude',...
    'AUC',...
    'NegativeArea',...
    'Slope'};

for r = 1:numel(cfgSPN.analysis_rois)

    roiName = ...
        cfgSPN.analysis_rois{r};

    for iw = 1:numel(cfgSPN.window_names)

        winName = ...
            cfgSPN.window_names{iw};

        for im = 1:numel(metrics)

            metric = ...
                metrics{im};

            con = [];
            dis = [];

            %% ============================================
            % SUBJECT VALUES
            %% ============================================

            for is = 1:numel(subs)

                con(end+1) = ...
                    SPN_Subj.(subs{is}) ...
                    .(roiName) ...
                    .(winName) ...
                    .Consonant ...
                    .(metric);

                dis(end+1) = ...
                    SPN_Subj.(subs{is}) ...
                    .(roiName) ...
                    .(winName) ...
                    .Dissonant ...
                    .(metric);

            end

            %% ============================================
            % STATS
            %% ============================================

            p = ...
                SPN_Stats.(roiName) ...
                .(winName) ...
                .(metric).p;

            d = ...
                SPN_Stats.(roiName) ...
                .(winName) ...
                .(metric).cohen_d;

            n = ...
                SPN_Stats.(roiName) ...
                .(winName) ...
                .(metric).n;

            %% ============================================
            % FIGURE
            %% ============================================

            figure( ...
                'Color','w',...
                'Position',[100 100 700 600]);

            hold on

            %% Subjects

            for k = 1:numel(con)

                plot( ...
                    [1 2],...
                    [con(k) dis(k)],...
                    '-o',...
                    'Color',...
                    [0.7 0.7 0.7]);

            end

            %% Consonant

            scatter( ...
                ones(size(con)),...
                con,...
                60,...
                [0 0.4470 0.7410],...
                'filled');

            %% Dissonant

            scatter( ...
                2*ones(size(dis)),...
                dis,...
                60,...
                [0.8500 0.3250 0.0980],...
                'filled');

            %% Mean ± SEM

            errorbar( ...
                1,...
                mean(con),...
                std(con)/sqrt(numel(con)),...
                'k',...
                'LineWidth',2);

            errorbar( ...
                2,...
                mean(dis),...
                std(dis)/sqrt(numel(dis)),...
                'k',...
                'LineWidth',2);

            %% Axes

            xlim([0.5 2.5])

            xticks([1 2])

            xticklabels({ ...
                'Consonant',...
                'Dissonant'});

            ylabel(metric)

            title(sprintf( ...
                '%s | %s\np = %.4f   d = %.2f   N = %d',...
                format_tex_name(roiName),...
                format_tex_name(winName),...
                p,...
                d,...
                n));

            grid on

            %% Save

            exportgraphics( ...
                gcf,...
                fullfile( ...
                metricDir,...
                sprintf('%s_%s_%s.png',...
                roiName,...
                winName,...
                metric)),...
                'Resolution',300);

            close

        end

    end

end

end