function plot_eran_zoom( ...
    subj_list,...
    cfgERAN,...
    outdir)

zoomDir = fullfile(outdir,'Zoom');

if ~exist(zoomDir,'dir')
    mkdir(zoomDir);
end

for r = 1:numel(cfgERAN.analysis_rois)

    roiName = cfgERAN.analysis_rois{r};

    roi_labels = ...
        cfgERAN.rois.(roiName);

    ERP_CON = [];
    ERP_DIS = [];

    for iSub = 1:numel(subj_list)

        data_trials = ...
            subj_list(iSub).data_trials;

        timeVec = ...
            data_trials(1).time;

        idxCon = strcmp( ...
            {data_trials.eventLabel}, ...
            'Consonant');

        idxDis = strcmp( ...
            {data_trials.eventLabel}, ...
            'Dissonant');

        ERPcon_trials = [];
        ERPdis_trials = [];

        for it = find(idxCon)

            labels = ...
                {data_trials(it).chanlocs.labels};

            roi_idx = ...
                ismember(labels,roi_labels);

            ERPcon_trials(end+1,:) = ...
                mean(data_trials(it).eeg(roi_idx,:),1);

        end

        for it = find(idxDis)

            labels = ...
                {data_trials(it).chanlocs.labels};

            roi_idx = ...
                ismember(labels,roi_labels);

            ERPdis_trials(end+1,:) = ...
                mean(data_trials(it).eeg(roi_idx,:),1);

        end

        ERP_CON(iSub,:) = ...
            mean(ERPcon_trials,1);

        ERP_DIS(iSub,:) = ...
            mean(ERPdis_trials,1);

    end

    ERPcon = mean(ERP_CON,1);

    ERPdis = mean(ERP_DIS,1);

    ERPdiff = ERPdis - ERPcon;

    %% ========================================================
    % PEAK DIFFERENCE (ERAN_FULL)
    %% ========================================================

    idxPeakWin = ...
        timeVec >= cfgN5.windows{end}(1) & ...
        timeVec <= cfgN5.windows{end}(2);

    diffWin = ERPdiff(idxPeakWin);

    timeWin = timeVec(idxPeakWin);

    [peakAmp,idxPeak] = ...
        min(diffWin);

    peakLat = ...
        timeWin(idxPeak);

    %% ========================================================
    % FIGURE
    %% ========================================================
    winLabels = cell(1,numel(cfgERAN.windows));

    for iw = 1:numel(cfgERAN.windows)

        win = cfgERAN.windows{iw};

        winLabels{iw} = sprintf( ...
            '%s (%d-%d ms)',...
            cfgERAN.window_names{iw},...
            round(win(1)*1000),...
            round(win(2)*1000));

    end
    figure( ...
        'Color','w',...
        'Position',[100 100 1200 600]);

    hold on

    yL = [ ...
        min([ERPcon ERPdis ERPdiff]) ...
        max([ERPcon ERPdis ERPdiff])];

    colors = lines(3);

    for iw = 1:numel(cfgERAN.windows)

        win = cfgERAN.windows{iw};

        patch( ...
            [win(1) win(2) win(2) win(1)],...
            [yL(1) yL(1) yL(2) yL(2)],...
            colors(iw,:),...
            'FaceAlpha',0.08,...
            'EdgeColor','none');

    end

    plot( ...
        timeVec,...
        ERPcon,...
        'LineWidth',2);

    plot( ...
        timeVec,...
        ERPdis,...
        'LineWidth',2);

    plot( ...
        timeVec,...
        ERPdiff,...
        'k',...
        'LineWidth',2);

    plot( ...
        peakLat,...
        peakAmp,...
        'rv',...
        'MarkerFaceColor','r',...
        'MarkerSize',8);

    xline( ...
        peakLat,...
        'r--',...
        'LineWidth',1.5);

    yline(0,'k:')
    xline(0,'k:')

    xlim(cfgERAN.zoom_window)

    xlabel('Time (s)')
    ylabel('\muV')

    title(sprintf( ...
        '%s ERAN Zoom\nPeak ERAN = %.0f ms | %.2f µV', ...
        roiName,...
        peakLat*1000,...
        peakAmp));

    legendLabels = [ ...
        winLabels,...
        {'Consonant',...
        'Dissonant',...
        'Difference',...
        'Peak ERAN'}];

    legend( ...
        legendLabels,...
        'Location','best');
    
    exportgraphics( ...
        gcf,...
        fullfile( ...
        zoomDir,...
        sprintf('%s_ERAN_Zoom.png', ...
        roiName)),...
        'Resolution',300);

    close

end