function require_model_files( ...
    modelName,...
    paramName)

assert( ...
    exist(modelName,'file')==2,...
    '%s.m not found', ...
    modelName);

assert( ...
    exist(paramName,'file')==2,...
    '%s.m not found', ...
    paramName);

end