function SPN_Stats = run_spn_statistics( ...
    SPN_Subj,...
    cfgSPN)

subs = fieldnames(SPN_Subj);

metrics = { ...
    'MeanAmplitude',...
    'AUC',...
    'NegativeArea',...
    'Slope'};

SPN_Stats = struct();

for r = 1:numel(cfgSPN.analysis_rois)

    roiName = cfgSPN.analysis_rois{r};

    for iw = 1:numel(cfgSPN.window_names)

        winName = ...
            cfgSPN.window_names{iw};

        for im = 1:numel(metrics)

            metric = metrics{im};

            consonant = [];
            dissonant = [];

            for is = 1:numel(subs)

                consonant(end+1) = ...
                    SPN_Subj.(subs{is}) ...
                    .(roiName) ...
                    .(winName) ...
                    .Consonant ...
                    .(metric);

                dissonant(end+1) = ...
                    SPN_Subj.(subs{is}) ...
                    .(roiName) ...
                    .(winName) ...
                    .Dissonant ...
                    .(metric);

            end

            validIdx = ...
                ~isnan(consonant) & ...
                ~isnan(dissonant);

            consonant = ...
                consonant(validIdx);

            dissonant = ...
                dissonant(validIdx);

            if numel(consonant) < 2

                h = NaN;
                p = NaN;
                ci = [NaN NaN];

                stats.tstat = NaN;
                stats.df    = NaN;

                cohen_d = NaN;

            else

                [h,p,ci,stats] = ttest( ...
                    dissonant,...
                    consonant);

                diffVals = ...
                    dissonant - consonant;

                if std(diffVals)==0

                    cohen_d = NaN;

                else

                    cohen_d = ...
                        mean(diffVals) / ...
                        std(diffVals);

                end

            end

            SPN_Stats.(roiName) ...
                .(winName) ...
                .(metric).h = h;

            SPN_Stats.(roiName) ...
                .(winName) ...
                .(metric).p = p;

            SPN_Stats.(roiName) ...
                .(winName) ...
                .(metric).ci = ci;

            SPN_Stats.(roiName) ...
                .(winName) ...
                .(metric).tstat = ...
                stats.tstat;

            SPN_Stats.(roiName) ...
                .(winName) ...
                .(metric).df = ...
                stats.df;

            SPN_Stats.(roiName) ...
                .(winName) ...
                .(metric).cohen_d = ...
                cohen_d;

            SPN_Stats.(roiName) ...
                .(winName) ...
                .(metric).n = ...
                numel(consonant);

        end

    end

end

end