function MMN_Stats = run_mmn_statistics( ...
    MMN_Subj,...
    cfgMMN)

subs = fieldnames(MMN_Subj);

metrics = { ...
    'MeanAmplitude',...
    'PeakAmplitude',...
    'PeakLatency',...
    'PeakToPeak',...
    'AUC',...
    'NegativeArea'};

MMN_Stats = struct();

for r = 1:numel(cfgMMN.analysis_rois)

    roiName = cfgMMN.analysis_rois{r};

    for iw = 1:numel(cfgMMN.window_names)

        winName = ...
            cfgMMN.window_names{iw};

        for im = 1:numel(metrics)

            metric = metrics{im};

            consonant = [];
            dissonant = [];

            for is = 1:numel(subs)

                consonant(end+1) = ...
                    MMN_Subj.(subs{is}) ...
                    .(roiName) ...
                    .(winName) ...
                    .Consonant ...
                    .(metric);

                dissonant(end+1) = ...
                    MMN_Subj.(subs{is}) ...
                    .(roiName) ...
                    .(winName) ...
                    .Dissonant ...
                    .(metric);

            end

            [h,p,ci,stats] = ttest( ...
                dissonant,...
                consonant);

            diffVals = ...
                dissonant - consonant;
          
            if std(diffVals)==0
                cohen_d = NaN;
            else
                cohen_d = ...
                    mean(diffVals)/std(diffVals);
            end
            
            MMN_Stats.(roiName) ...
                .(winName) ...
                .(metric).h = h;

            MMN_Stats.(roiName) ...
                .(winName) ...
                .(metric).p = p;

            MMN_Stats.(roiName) ...
                .(winName) ...
                .(metric).ci = ci;

            MMN_Stats.(roiName) ...
                .(winName) ...
                .(metric).tstat = ...
                stats.tstat;

            MMN_Stats.(roiName) ...
                .(winName) ...
                .(metric).df = ...
                stats.df;

            MMN_Stats.(roiName) ...
                .(winName) ...
                .(metric).cohen_d = ...
                cohen_d;

        end
    end
end