function [TrainEEG,...
          TestEEG,...
          outClassifier,...
          PredField,...
          ProbField] = ...
          run_classifier_fold( ...
          TrainEEG,...
          TestEEG,...
          classifierName,...
          par)

%% ============================================================
% INPUT VALIDATION
%% ============================================================
assert(~isempty(TrainEEG), ...
    'TrainEEG is empty');

assert(~isempty(TestEEG), ...
    'TestEEG is empty');

assert(ischar(classifierName) || isstring(classifierName), ...
    'classifierName must be string');

assert(isstruct(par), ...
    'par must be struct');

classifierName = ...
    upper(char(classifierName));

%% ============================================================
% SUPPORTED CLASSIFIERS
%% ============================================================
supportedClassifiers = { ...
    'LDA',...    % Discriminant Analysis
    'QDA',...
    'LOGREG',... % Logistic Regression
    'KNN',... % Nearest Neighbour
    'NB',... % Probabilistic
    'SVC',... % Support Vector Machine
    'TREE',... % Decision Tree
    'RF',... % Random Forest
    'BAG',... % Ensemble Methods
    'ADABOOST',...
    'RUSBOOST',...
    'SUBSPACE',...
    'ENSEMBLE',...
    'ECOC',... % ECOC
    'ANN',... % Artificial Neural Network
    'MLP',...
    'CNN',...
    'LSTM'...
    };

assert( ...
    ismember( ...
    classifierName,...
    supportedClassifiers),...
    'Unsupported classifier: %s',...
    classifierName);

%% ============================================================
% TOOLBOX CHECK
%% ============================================================
classifier_toolbox_check( ...
    classifierName);

%% ============================================================
% CLASSIFIER DISPATCH
%% ============================================================
switch classifierName

%% ============================================================
% DISCRIMINANT
%% ============================================================

    case 'LDA'

        require_model_files( ...
            'ldaModel',...
            'ldaModelParams');

        par.ldaModel = ...
            ldaModelParams(par);

        [TrainEEG,outClassifier] = ...
            ldaModel( ...
            TrainEEG,...
            par.ldaModel);

        PredField = 'LDApred';
        ProbField = 'LDAProb';

    case 'QDA'

        require_model_files( ...
            'qdaModel',...
            'qdaModelParams');

        par.qdaModel = ...
            qdaModelParams(par);

        [TrainEEG,outClassifier] = ...
            qdaModel( ...
            TrainEEG,...
            par.qdaModel);

        PredField = 'QDApred';
        ProbField = 'QDAProb';

%% ============================================================
% LOGISTIC REGRESSION
%% ============================================================

    case 'LOGREG'

        require_model_files( ...
            'logregModel',...
            'logregModelParams');

        par.logregModel = ...
            logregModelParams(par);

        [TrainEEG,outClassifier] = ...
            logregModel( ...
            TrainEEG,...
            par.logregModel);

        PredField = 'LOGREGpred';
        ProbField = 'LOGREGProb';

%% ============================================================
% KNN
%% ============================================================

    case 'KNN'

        require_model_files( ...
            'knnModel',...
            'knnModelParams');

        par.knnModel = ...
            knnModelParams(par);

        [TrainEEG,outClassifier] = ...
            knnModel( ...
            TrainEEG,...
            par.knnModel);

        PredField = 'KNNpred';
        ProbField = 'KNNProb';

%% ============================================================
% NAIVE BAYES
%% ============================================================

    case 'NB'

        require_model_files( ...
            'nbModel',...
            'nbModelParams');

        par.nbModel = ...
            nbModelParams(par);

        [TrainEEG,outClassifier] = ...
            nbModel( ...
            TrainEEG,...
            par.nbModel);

        PredField = 'NBpred';
        ProbField = 'NBProb';

%% ============================================================
% SVM
%% ============================================================

    case 'SVC'

        require_model_files( ...
            'svcModel',...
            'svcModelParams');

        par.svcModel = ...
            svcModelParams(par);

        [TrainEEG,outClassifier] = ...
            svcModel( ...
            TrainEEG,...
            par.svcModel);

        PredField = 'SVCpred';
        ProbField = 'SVCProb';

%% ============================================================
% TREE METHODS
%% ============================================================

    case 'TREE'

        require_model_files( ...
            'treeModel',...
            'treeModelParams');

        par.treeModel = ...
            treeModelParams(par);

        [TrainEEG,outClassifier] = ...
            treeModel( ...
            TrainEEG,...
            par.treeModel);

        PredField = 'TREEpred';
        ProbField = 'TREEProb';

    case 'RF'

        require_model_files( ...
            'rfModel',...
            'rfModelParams');

        par.rfModel = ...
            rfModelParams(par);

        [TrainEEG,outClassifier] = ...
            rfModel( ...
            TrainEEG,...
            par.rfModel);

        PredField = 'RFpred';
        ProbField = 'RFProb';

    case 'BAG'

        require_model_files( ...
            'bagModel',...
            'bagModelParams');

        par.bagModel = ...
            bagModelParams(par);

        [TrainEEG,outClassifier] = ...
            bagModel( ...
            TrainEEG,...
            par.bagModel);

        PredField = 'BAGpred';
        ProbField = 'BAGProb';

    case 'ADABOOST'

    require_model_files( ...
        'adaboostModel',...
        'adaboostModelParams');

    par.adaboostModel = ...
        adaboostModelParams(par);

    [TrainEEG,outClassifier] = ...
        adaboostModel( ...
        TrainEEG,...
        par.adaboostModel);

    PredField = 'ADABOOSTpred';
    ProbField = 'ADABOOSTProb';

    case 'RUSBOOST'

        require_model_files( ...
            'rusboostModel',...
            'rusboostModelParams');

        par.rusboostModel = ...
            rusboostModelParams(par);

        [TrainEEG,outClassifier] = ...
            rusboostModel( ...
            TrainEEG,...
            par.rusboostModel);

        PredField = 'RUSBOOSTpred';
        ProbField = 'RUSBOOSTProb';
case 'SUBSPACE'

    require_model_files( ...
        'subspaceModel',...
        'subspaceModelParams');

    par.subspaceModel = ...
        subspaceModelParams(par);

    [TrainEEG,outClassifier] = ...
        subspaceModel( ...
        TrainEEG,...
        par.subspaceModel);

    PredField = 'SUBSPACEpred';
    ProbField = 'SUBSPACEProb';
case 'ENSEMBLE'

    require_model_files( ...
        'ensembleModel',...
        'ensembleModelParams');

    par.ensembleModel = ...
        ensembleModelParams(par);

    [TrainEEG,outClassifier] = ...
        ensembleModel( ...
        TrainEEG,...
        par.ensembleModel);

    PredField = 'ENSEMBLEpred';
    ProbField = 'ENSEMBLEProb';

%% ============================================================
% ECOC
%% ============================================================

    case 'ECOC'

    require_model_files( ...
        'ecocModel',...
        'ecocModelParams');

    par.ecocModel = ...
        ecocModelParams(par);

    [TrainEEG,outClassifier] = ...
        ecocModel( ...
        TrainEEG,...
        par.ecocModel);

    PredField = 'ECOCpred';
    ProbField = 'ECOCProb';
%% ============================================================
% NEURAL NETWORKS
%% ============================================================

    case 'ANN'

        require_model_files( ...
            'annModel',...
            'annModelParams');

        par.annModel = ...
            annModelParams(par);

        [TrainEEG,outClassifier] = ...
            annModel( ...
            TrainEEG,...
            par.annModel);

        PredField = 'ANNpred';
        ProbField = 'ANNProb';

%% ============================================================
% FUTURE
%% ============================================================

    case 'MLP'

        require_model_files( ...
            'mlpModel',...
            'mlpModelParams');

        par.mlpModel = ...
            mlpModelParams(par);

        [TrainEEG,outClassifier] = ...
            mlpModel( ...
            TrainEEG,...
            par.mlpModel);

        PredField = 'MLPpred';
        ProbField = 'MLPProb';

    case 'CNN'

        require_model_files( ...
            'cnnModel',...
            'cnnModelParams');

        par.cnnModel = ...
            cnnModelParams(par);

        [TrainEEG,outClassifier] = ...
            cnnModel( ...
            TrainEEG,...
            par.cnnModel);

        PredField = 'CNNpred';
        ProbField = 'CNNProb';

    case 'LSTM'

        require_model_files( ...
            'lstmModel',...
            'lstmModelParams');

        par.lstmModel = ...
            lstmModelParams(par);

        [TrainEEG,outClassifier] = ...
            lstmModel( ...
            TrainEEG,...
            par.lstmModel);

        PredField = 'LSTMpred';
        ProbField = 'LSTMProb';

    otherwise

        error( ...
            'Unsupported classifier: %s',...
            classifierName);

end

end