function ERAN_Stats = run_eran_statistics( ...
    ERAN_Subj,...
    cfgERAN)

subs = fieldnames(ERAN_Subj);

metrics = { ...
    'MeanAmplitude',...
    'PeakAmplitude',...
    'PeakLatency',...
    'PeakToPeak',...
    'AUC',...
    'NegativeArea'};

ERAN_Stats = struct();

for r = 1:numel(cfgERAN.analysis_rois)

    roiName = cfgERAN.analysis_rois{r};

    for iw = 1:numel(cfgERAN.window_names)

        winName = ...
            cfgERAN.window_names{iw};

        for im = 1:numel(metrics)

            metric = metrics{im};

            consonant = [];
            dissonant = [];

            for is = 1:numel(subs)

                consonant(end+1) = ...
                    ERAN_Subj.(subs{is}) ...
                    .(roiName) ...
                    .(winName) ...
                    .Consonant ...
                    .(metric);

                dissonant(end+1) = ...
                    ERAN_Subj.(subs{is}) ...
                    .(roiName) ...
                    .(winName) ...
                    .Dissonant ...
                    .(metric);

            end

            [h,p,ci,stats] = ttest( ...
                dissonant,...
                consonant);

            diffVals = ...
                dissonant - consonant;
          
            if std(diffVals)==0
                cohen_d = NaN;
            else
                cohen_d = ...
                    mean(diffVals)/std(diffVals);
            end
            
            ERAN_Stats.(roiName) ...
                .(winName) ...
                .(metric).h = h;

            ERAN_Stats.(roiName) ...
                .(winName) ...
                .(metric).p = p;

            ERAN_Stats.(roiName) ...
                .(winName) ...
                .(metric).ci = ci;

            ERAN_Stats.(roiName) ...
                .(winName) ...
                .(metric).tstat = ...
                stats.tstat;

            ERAN_Stats.(roiName) ...
                .(winName) ...
                .(metric).df = ...
                stats.df;

            ERAN_Stats.(roiName) ...
                .(winName) ...
                .(metric).cohen_d = ...
                cohen_d;

        end
    end
end