function Results = run_fbcsp_fold( ...
    TrainTrials,...
    TestTrials,...
    cfgFBCSP)

%% ============================================================
% INITIALIZATION
%% ============================================================

signal_name = 'eeg';
signal_process = 'CSP';

%% ============================================================
% PREPARE TRAIN
%% ============================================================

TrainEEG = prepare_fbcsp_trials( ...
    TrainTrials);

%% ============================================================
% PREPARE TEST
%% ============================================================

TestEEG = prepare_fbcsp_trials( ...
    TestTrials);

%% ============================================================
% FILTER BANK TRAIN
%% ============================================================

par = struct();

par.FilterBankCompute = ...
    FilterBankComputeParams();

par.FilterBankCompute.exec = false;

par.FilterBankCompute.InField = ...
    signal_name;

par.FilterBankCompute.OutField = ...
    signal_name;

par.FilterBankCompute.FilterBank = ...
    cfgFBCSP.filterBankName;

par.FilterBankCompute.fsample = ...
    TrainTrials(1).srate;

par.exec.funname = ...
    {'FilterBankCompute'};

[TrainEEG,~] = ...
    run_trials( ...
    TrainEEG,...
    par);

%% ============================================================
% FILTER BANK TEST
%% ============================================================

[TestEEG,~] = ...
    run_trials( ...
    TestEEG,...
    par);

%% ============================================================
% CSP MODEL (TRAIN ONLY)
%% ============================================================

par.cspModel = ...
    cspModelParams();

par.cspModel.m = ...
    cfgFBCSP.csp_components;

par.cspModel.InField = ...
    signal_name;

par.cspModel.OutField = ...
    signal_process;

[~,out.cspModel] = ...
    cspModel( ...
    TrainEEG,...
    par.cspModel);

%% ============================================================
% CSP ENCODE TRAIN
%% ============================================================

par.cspEncode = ...
    cspEncodeParams();

par.cspEncode.InField = ...
    signal_name;

par.cspEncode.OutField = ...
    signal_process;

par.cspEncode.W = ...
    out.cspModel.W;

par.exec.funname = ...
    {'cspEncode'};

TrainEEG = ...
    run_trials( ...
    TrainEEG,...
    par);

%% ============================================================
% CSP ENCODE TEST
%% ============================================================

TestEEG = ...
    run_trials( ...
    TestEEG,...
    par);

%% ============================================================
% MI MODEL (TRAIN ONLY)
%% ============================================================

par.miModel = ...
    miModelParams();

par.miModel.InField = ...
    signal_process;

par.miModel.m = ...
    par.cspModel.m;

par.miModel.k = ...
    cfgFBCSP.mi_k;

[~,out.miModel] = ...
    miModel( ...
    TrainEEG,...
    par.miModel);

%% ============================================================
% MI ENCODE PARAMETERS
%% ============================================================

par.miEncode = ...
    miEncodeParams();

par.miEncode.InField = ...
    signal_process;

par.miEncode.OutField = ...
    signal_process;

par.miEncode.nclass = ...
    unique([TrainEEG.trialType]');

par.miEncode.IndMI = ...
    out.miModel.IndMI;

par.exec.funname = ...
    {'miEncode'};

%% ============================================================
% MI ENCODE TRAIN
%% ============================================================

TrainEEG = ...
    run_trials( ...
    TrainEEG,...
    par);

%% ============================================================
% MI ENCODE TEST
%% ============================================================

TestEEG = ...
    run_trials( ...
    TestEEG,...
    par);

%% ============================================================
% CLASSIFIER MODEL
%% ============================================================

switch upper(cfgFBCSP.classifier)

    case 'QDA'

        par.qdaModel = ...
            qdaModelParams();

        par.qdaModel.InField = ...
            signal_process;

        [TrainEEG,outClassifier] = ...
            qdaModel( ...
            TrainEEG,...
            par.qdaModel);

        PredField = 'QDApred';
        ProbField = 'QDAProb';

    case 'KNN'

        par.knnModel = ...
            knnModelParams();

        par.knnModel.InField = ...
            signal_process;

        [TrainEEG,outClassifier] = ...
            knnModel( ...
            TrainEEG,...
            par.knnModel);

        PredField = 'KNNpred';
        ProbField = 'KNNProb';

    case 'NB'

        par.nbModel = ...
            nbModelParams();

        par.nbModel.InField = ...
            signal_process;

        [TrainEEG,outClassifier] = ...
            nbModel( ...
            TrainEEG,...
            par.nbModel);

        PredField = 'NBpred';
        ProbField = 'NBProb';

    case 'SVC'

        par.svcModel = ...
            svcModelParams();

        par.svcModel.InField = ...
            signal_process;

        [TrainEEG,outClassifier] = ...
            svcModel( ...
            TrainEEG,...
            par.svcModel);

        PredField = 'SVCpred';
        ProbField = 'SVCProb';

    otherwise

        error('Unsupported classifier: %s', ...
            cfgFBCSP.classifier);

end

%% ============================================================
% MODEL PREDICTION
%% ============================================================

par.mdlPredict = ...
    mdlPredictParams();

par.mdlPredict.InField = ...
    signal_process;

par.mdlPredict.OutField = ...
    PredField;

par.mdlPredict.ProbField = ...
    ProbField;

par.mdlPredict.mdl = ...
    outClassifier.mdl;

[TrainEEG,resClassifier.train] = ...
    mdlPredict( ...
    TrainEEG,...
    par.mdlPredict);

[TestEEG,resClassifier.test] = ...
    mdlPredict( ...
    TestEEG,...
    par.mdlPredict);

%% ============================================================
% LABELS
%% ============================================================

Ytrain_true = ...
    [TrainEEG.trialType]';

Ytrain_pred = ...
    [TrainEEG.(PredField)]';

Ytest_true = ...
    [TestEEG.trialType]';

Ytest_pred = ...
    [TestEEG.(PredField)]';

%% ============================================================
% TRAIN METRICS
%% ============================================================

CMtrain = ...
    confusionmat( ...
    Ytrain_true,...
    Ytrain_pred,...
    'Order',[1 2]);

ACCtrain = ...
    mean(Ytrain_true == Ytrain_pred);

SensTrain = ...
    CMtrain(1,1) / max(1,sum(CMtrain(1,:)));

SpecTrain = ...
    CMtrain(2,2) / max(1,sum(CMtrain(2,:)));

BATrain = ...
    mean([SensTrain SpecTrain]);

%% ============================================================
% TEST METRICS
%% ============================================================

CMtest = ...
    confusionmat( ...
    Ytest_true,...
    Ytest_pred,...
    'Order',[1 2]);

ACCtest = ...
    mean(Ytest_true == Ytest_pred);

SensTest = ...
    CMtest(1,1) / max(1,sum(CMtest(1,:)));

SpecTest = ...
    CMtest(2,2) / max(1,sum(CMtest(2,:)));

BATest = ...
    mean([SensTest SpecTest]);

%% ============================================================
% OUTPUT
%% ============================================================

Results = struct();

Results.classifier = ...
    cfgFBCSP.classifier;

Results.testSubject = ...
    TestTrials(1).subjectID;

Results.nTrainTrials = ...
    length(TrainTrials);

Results.nTestTrials = ...
    length(TestTrials);

Results.nFeatures = ...
    size(TrainEEG(1).(signal_process),2);

Results.W = ...
    out.cspModel.W;

Results.IndMI = ...
    out.miModel.IndMI;

Results.mdl = ...
    outClassifier.mdl;

Results.Ytrain_true = ...
    Ytrain_true;

Results.Ytrain_pred = ...
    Ytrain_pred;

Results.Ytest_true = ...
    Ytest_true;

Results.Ytest_pred = ...
    Ytest_pred;

Results.CMtrain = ...
    CMtrain;

Results.CMtest = ...
    CMtest;

Results.ACCtrain = ...
    ACCtrain;

Results.ACCtest = ...
    ACCtest;

Results.BATrain = ...
    BATrain;

Results.BATest = ...
    BATest;

Results.Sensitivity = ...
    SensTest;

Results.Specificity = ...
    SpecTest;

Results.resClassifier_train = ...
    resClassifier.train;

Results.resClassifier_test = ...
    resClassifier.test;

%% ============================================================
% SUMMARY
%% ============================================================

fprintf('\n');

fprintf('[%s] Train ACC : %.2f %%\n', ...
    cfgFBCSP.classifier,...
    100*ACCtrain);

fprintf('[%s] Train BA  : %.2f %%\n', ...
    cfgFBCSP.classifier,...
    100*BATrain);

fprintf('[%s] Test ACC  : %.2f %%\n', ...
    cfgFBCSP.classifier,...
    100*ACCtest);

fprintf('[%s] Test BA   : %.2f %%\n', ...
    cfgFBCSP.classifier,...
    100*BATest);

fprintf('--------------------------------\n');