function Ranking = ...
    step10A_rank_features( ...
    Results,...
    cfgFD)

Ranking = table();

Ranking.Feature = ...
    string(Results.Feature);

Ranking.AUC = ...
    Results.AUC;

Ranking.CohenD = ...
    Results.CohenD;

Ranking.pValue = ...
    Results.pValue;

Ranking.ScoreAUC = ...
    abs(Ranking.AUC - 0.5);

Ranking.ScoreD = ...
    abs(Ranking.CohenD);

Ranking.ScoreCombined = ...
    abs(Ranking.CohenD) .* ...
    (-log10( ...
    max(Ranking.pValue,eps)));

Ranking.AUCRank = ...
    tiedrank( ...
    -Ranking.ScoreAUC);

Ranking.DRank = ...
    tiedrank( ...
    -Ranking.ScoreD);

Ranking.CombinedRank = ...
    tiedrank( ...
    -Ranking.ScoreCombined);

Ranking = ...
    sortrows( ...
    Ranking,...
    'CombinedRank');

end