function cfgINF = ...
    update_erpinf_feature_flags( ...
    cfgINF,...
    FeatureNames)

FeatureNames = ...
    string(FeatureNames);

%% ============================================================
% ERPINDEX
%% ============================================================

cfgINF.useERPIndex = ...
    any( ...
    contains( ...
    FeatureNames,...
    'ERPIndex'));

%% ============================================================
% ERAN_B
%% ============================================================

cfgINF.useERANB = ...
    any( ...
    contains( ...
    FeatureNames,...
    '_ERAN_B_') & ...
    ~contains( ...
    FeatureNames,...
    'BetaLow'));

%% ============================================================
% BETALOW
%% ============================================================

cfgINF.useBetaLow = ...
    any( ...
    contains( ...
    FeatureNames,...
    'BetaLow'));

end